### ISSUE TITLE
dies on start

### ISSUE THREAD

**Issue by indeyets** [rubyunworks/yaml_command#4]
I just installed command using gem on OS X 10.8.2. I am using ruby 1.9.3-p327 from [homebrew](http://mxcl.github.com/homebrew/)

```
[…]$ yaml 
/opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/gems/yaml_command-0.1.0/lib/yaml_command/base.rb:24:in `<class:Command>': undefined method `alias_switch' for YAMLCommand::Command:Class (NoMethodError)
    from /opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/gems/yaml_command-0.1.0/lib/yaml_command/base.rb:5:in `<module:YAMLCommand>'
    from /opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/gems/yaml_command-0.1.0/lib/yaml_command/base.rb:1:in `<top (required)>'
    from /opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/gems/yaml_command-0.1.0/lib/yaml_command.rb:4:in `<top (required)>'
    from /opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/homebrew/Cellar/ruby/1.9.3-p327/lib/ruby/gems/1.9.1/gems/yaml_command-0.1.0/bin/yaml:2:in `<top (required)>'
    from /opt/homebrew/bin/yaml:23:in `load'
    from /opt/homebrew/bin/yaml:23:in `<main>'
```

**Comment by trans** [comment]
Maybe the dependency on Executable gem is off in someway (that's where `alias_switch` comes from). `gem install executable` to make sure you have the latest. And I'll look into it on my end. Thanks!

**Comment by trans** [comment]
Ok. Problem was pretty simple. I hadn't released the latest version of Executable yet. Just pushed 1.2.1, so that should fix the problem.

**Comment by indeyets** [comment]
it helped, thanks!
does Gem allow specifying minimum version requirement for dependencies? that would be the proper solution, I guess

**Comment by trans** [comment]
True. I hadn't done so b/c they are still pretty nascent, but it's getting to that point.

Big thanks for reporting, btw! It always surprises me the number of people who don't ever bother.
