### ISSUE TITLE
Needs examples

### ISSUE THREAD

**Issue by kerphi** [rubyunworks/yaml_command#8]
Without example it's complicated to understand how to use for example the "set" command.
I tried:

```
yaml set analogist.image myvalue ./docker-compose.yml
```

without any success

**Comment by jonhiggs** [comment]
me too.

**Comment by pboling** [comment]
Also 👍
Trying to figure out how to create a YAML file from the command line.  If I use `yaml get` before creating the file it is stuck in an infinite loop.  If I use `yaml set` before creating the file it also appears to be in an infinite loop.

UPDATE: even if I `touch` the file first so it exists the code still hangs trying to read the file.

```
touch ~/.example.yml
yaml get -f ~/.example.yml
^C/Users/peterboling/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:370:in `read': Interrupt
    from /Users/peterboling/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:370:in `parse'
    from /Users/peterboling/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
    from /Users/peterboling/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:318:in `parse'
    from /Users/peterboling/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:245:in `load'
    from /Users/peterboling/.rvm/gems/ruby-2.2.3/gems/yaml_command-0.1.1/lib/yaml_command/base.rb:115:in `data'
    from /Users/peterboling/.rvm/gems/ruby-2.2.3/gems/yaml_command-0.1.1/lib/yaml_command/get.rb:7:in `call'
    from /Users/peterboling/.rvm/gems/ruby-2.2.3/gems/executable-1.2.1/lib/executable/domain.rb:100:in `execute'
    from /Users/peterboling/.rvm/gems/ruby-2.2.3/gems/yaml_command-0.1.1/bin/yaml:4:in `<top (required)>'
```
